import fs from 'node:fs/promises';
import path from 'node:path';
const root=import.meta.dirname;
const inventoryInitial=JSON.parse(await fs.readFile(path.join(root,'inventory-initial.json'),'utf8'));
const pivotInventorySeed=JSON.parse(await fs.readFile(path.join(root,'pivot-inventory.snapshot.json'),'utf8'));
const inventoryCode='const inventoryInitial='+JSON.stringify(inventoryInitial)+';\nconst pivotInventorySeed='+JSON.stringify(pivotInventorySeed)+';\n'+(await fs.readFile(path.join(root,'pivot-inventory.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'inventory-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const dest=path.join(root,'dist/server');await fs.mkdir(dest,{recursive:true});
const assets={};const types={'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.txt':'text/plain'};
async function walk(dir,rel=''){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const key=path.join(rel,entry.name);if(entry.isDirectory())await walk(path.join(dir,entry.name),key);else if(!['snapshot.json','_headers'].includes(key))assets['/'+key]={type:types[path.extname(key)]||'application/octet-stream',body:(await fs.readFile(path.join(dir,entry.name))).toString('base64')};}}
await walk(path.join(root,'out'));
// All Event pages use the same top tabs and load only their selected view.
const {eventPages}=await import('./out/assets/event-pages.mjs');
const eventShell=await fs.readFile(path.join(root,'out/events.html'),'utf8');
for(const page of eventPages.slice(1))assets[page.path+'.html']={type:'text/html; charset=utf-8',body:Buffer.from(eventShell.replace('<title>Event Overview · VING</title>',`<title>${page.title} · VING</title>`)).toString('base64')};

const fallback=JSON.parse(await fs.readFile(path.join(root,'out/snapshot.json')));
const sanitizer=await fs.readFile(path.join(root,'sanitize.mjs'),'utf8');
const cloudWorkspace='const {handleCloudData,mergeCloudSnapshot,isLegacyCloudPath}=(()=>{'+(await fs.readFile(path.join(root,'cloud-data.mjs'),'utf8')).replace(/export /g,'')+';return {handleCloudData,mergeCloudSnapshot,isLegacyCloudPath};})();';
const onlineSales='const {applyOnlineSales,handleOnlineSales}=(()=>{'+(await fs.readFile(path.join(root,'online-sales-parser.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'online-sales.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {applyOnlineSales,handleOnlineSales};})();';
const cloudSales=(await fs.readFile(path.join(root,'cloud-sales.mjs'),'utf8')).replace(/^import .*;\n/gm,'');
const branchMapping=(await fs.readFile(path.join(root,'out/assets/branch-mapping.mjs'),'utf8')).replace(/export /g,'');
const eventsData='const {applyEventSales}=(()=>{'+branchMapping+'\n'+(await fs.readFile(path.join(root,'events-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {applyEventSales};})();';
const profitLossFallback=JSON.parse(await fs.readFile(path.join(root,'profit-loss.snapshot.json'),'utf8'));
const profitLoss='const {loadProfitLoss}=(()=>{'+(await fs.readFile(path.join(root,'profit-loss-data.mjs'),'utf8')).replace(/export /g,'')+';return {loadProfitLoss};})();';
const proposals='const {loadEventProposals}=(()=>{'+(await fs.readFile(path.join(root,'event-proposals-data.mjs'),'utf8')).replace(/export /g,'')+';return {loadEventProposals};})();';
const costSnapshot=JSON.parse(await fs.readFile(path.join(root,'product-cost.snapshot.json'),'utf8'));
const {productCostItems,productCostSource}=await import('./product-cost-data.mjs');
const productCostFallback={version:1,source:{...productCostSource,fetched_at:costSnapshot.importedAt,status:'saved'},items:productCostItems(costSnapshot.rows)};
const productCosts='const {loadProductCosts}=(()=>{'+(await fs.readFile(path.join(root,'product-cost-data.mjs'),'utf8')).replace(/export /g,'')+';return {loadProductCosts};})();';
const rebrand='const {loadRebrand}=(()=>{'+(await fs.readFile(path.join(root,'rebrand-data.mjs'),'utf8')).replace(/export /g,'')+';return {loadRebrand};})();';
const predictFallback=JSON.parse(await fs.readFile(path.join(root,'event-predict.snapshot.json'),'utf8'));
const planningFields=(await fs.readFile(path.join(root,'out/assets/event-planning-fields.mjs'),'utf8')).replace(/export /g,'');
const eventImages='const {eventImageIds,sameEventImages,resolveEventImages,uploadEventImage,readEventImage}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/event-image-rules.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'event-images.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {eventImageIds,sameEventImages,resolveEventImages,uploadEventImage,readEventImage};})();';
const compensation='const {compensationContext,estimateCompensation,compensationSalesTarget,compensationProfilesFor}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/event-compensation-data.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'out/assets/event-compensation.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {compensationContext,estimateCompensation,compensationSalesTarget,compensationProfilesFor};})();';
const predict='const {loadPredictData,predictWithin,mergeVenueDatabase,createEventRequest,updateEventRequest,listEventRequests}=(()=>{'+planningFields+'\n'+compensation+'\n'+ 'const {eventDateRange}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/event-forecast.mjs'),'utf8')).replace(/export /g,'')+';return {eventDateRange};})();\n'+(await fs.readFile(path.join(root,'out/assets/event-predict-model.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+branchMapping+'\n'+(await fs.readFile(path.join(root,'event-venue-database.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'event-predict-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'event-requests.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadPredictData,predictWithin,mergeVenueDatabase,createEventRequest,updateEventRequest,listEventRequests};})();';
const deletions='const {visibleProposals,deleteEventProposal,approveEventProposal,updateEventWorkflow,eventProposalDetail,summaryApprovedProposals,eventSchedulingFields}=(()=>{'+(await fs.readFile(path.join(root,'event-proposal-deletions.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {visibleProposals,deleteEventProposal,approveEventProposal,updateEventWorkflow,eventProposalDetail,summaryApprovedProposals,eventSchedulingFields};})();';
const mobilePush='const {handleMobilePush,revokeMobilePush,dispatchMobilePush,mobilePushReady}=(()=>{'+(await fs.readFile(path.join(root,'web-push.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'mobile-push.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {handleMobilePush,revokeMobilePush,dispatchMobilePush,mobilePushReady};})();';
const notifications=(await fs.readFile(path.join(root,'notifications.mjs'),'utf8')).replace(/export /g,'');
const operations='const {loadOperations,applyOperations,latestOperation}=(()=>{'+(await fs.readFile(path.join(root,'operations-live.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadOperations,applyOperations,latestOperation};})();';
const contracts=operations+'\nconst {loadContractWorkspace,updateContractWorkspace}=(()=>{'+(await fs.readFile(path.join(root,'contracts-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadContractWorkspace,updateContractWorkspace};})();';
const comparisonFallback=(await import('./out/assets/daily-comparison-data.mjs')).reportData;
const comparisonLive='const {loadComparison}=(()=>{const comparisonFallback='+JSON.stringify(comparisonFallback)+';'+(await fs.readFile(path.join(root,'daily-comparison-live.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadComparison};})();';
const branchStock=(await fs.readFile(path.join(root,'branch-stock.mjs'),'utf8')).replace(/export /g,'');
const warehouse=(await fs.readFile(path.join(root,'warehouse-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const stockForecast=(await fs.readFile(path.join(root,'stock-forecast-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const analysis='const {handleAnalysis}=(()=>{'+branchMapping+'\n'+
 (await fs.readFile(path.join(root,'out/assets/sales-channels.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+
 'const {compareForecasts,comparisonKey}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/sales-yoy.mjs'),'utf8')).replace(/export /g,'')+';return {compareForecasts,comparisonKey};})();\n'+
 (await fs.readFile(path.join(root,'out/assets/stock-grid.mjs'),'utf8')).match(/export function stockGridIdentity\(item\)\{[\s\S]*?\n\}/)[0].replace('export ','')+'\n'+
 (await fs.readFile(path.join(root,'analysis-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {handleAnalysis};})();';
const stockReport=(await fs.readFile(path.join(root,'stock-report-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const accessPermissions=(await fs.readFile(path.join(root,'out/assets/access-permissions.mjs'),'utf8')).replace(/export /g,'');
const activities='const {readActivityWorkspace,activitySources,saveActivityWorkspace}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/activity-model.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'activities-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {readActivityWorkspace,activitySources,saveActivityWorkspace};})();';
const stockSummary='const {loadStockSummary}=(()=>{const summaryPivotSeed='+JSON.stringify(JSON.parse(await fs.readFile(path.join(root,'pivot-inventory.snapshot.json'),'utf8')))+';\n'+(await fs.readFile(path.join(root,'out/assets/stock-summary-model.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'out/assets/stock-history.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'stock-summary-sales-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'stock-summary-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadStockSummary};})();';
const promotionForecast='const {buildForecastRows}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/stock-grid.mjs'),'utf8')).match(/export function stockGridIdentity\(item\)\{[\s\S]*?\n\}/)[0].replace('export ','')+'\n'+(await fs.readFile(path.join(root,'out/assets/stock-filters.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'out/assets/stock-forecast-model.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/^export \{.*\} from .*;\n/gm,'').replace(/export /g,'')+';return {buildForecastRows};})();';
const promotionScheduleCode='const {promotionEventOption,promotionSchedule,promotionScheduleError}=(()=>{const {eventDateRange}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/event-forecast.mjs'),'utf8')).replace(/export /g,'')+';return {eventDateRange};})();\n'+(await fs.readFile(path.join(root,'out/assets/promotion-schedule.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {promotionEventOption,promotionSchedule,promotionScheduleError};})();';
const promotionEvents='const {loadPromotionEvents,promotionEventDetail}=(()=>{'+(await fs.readFile(path.join(root,'promotion-events-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {loadPromotionEvents,promotionEventDetail};})();';
const promotions='const {readPromotionPlans,promotionStock,savePromotionPlan,changePromotionPlan,readPromotionHistory}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/stock-summary-model.mjs'),'utf8')).replace(/export /g,'')+'\n'+promotionForecast+'\n'+(await fs.readFile(path.join(root,'out/assets/stock-history.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'out/assets/promotion-model.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'promotion-forecast-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'promotions-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {readPromotionPlans,promotionStock,savePromotionPlan,changePromotionPlan,readPromotionHistory};})();';
const summaryDeletions='const {readSummaryEventDeletions,deleteSummaryEvent}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/summary-event-key.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'summary-event-deletions.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {readSummaryEventDeletions,deleteSummaryEvent};})();';
const workspaceDrafts=(await fs.readFile(path.join(root,'workspace-drafts.mjs'),'utf8')).replace(/export /g,'');
const gpCode='const {handleBranchProfit}=(()=>{const branchProfitSeed='+JSON.stringify(JSON.parse(await fs.readFile(path.join(root,'branch-profit.snapshot.json'),'utf8')))+';'+(await fs.readFile(path.join(root,'out/assets/branch-profit-model.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'branch-profit-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {handleBranchProfit:(request,env)=>handleBranchProfit(request,env,branchProfitSeed)};})();';
const scheduleCode='const {loadEventSchedule}=(()=>{'+(await fs.readFile(path.join(root,'event-logistics-data.mjs'),'utf8')).replace(/export /g,'')+';return {loadEventSchedule};})();';
const refreshCode='const {refreshPlan,refreshSource}=(()=>{'+(await fs.readFile(path.join(root,'data-refresh.mjs'),'utf8')).replace(/export /g,'')+';return {refreshPlan,refreshSource};})();';
const staffCode='const {handleEventStaff}=(()=>{'+(await fs.readFile(path.join(root,'out/assets/event-logistics.mjs'),'utf8')).replace(/export /g,'')+'\n'+(await fs.readFile(path.join(root,'event-staff-data.mjs'),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'')+';return {handleEventStaff};})();';
const worker=cloudWorkspace+'\n'+staffCode+'\n'+refreshCode+'\n'+scheduleCode+'\n'+gpCode+'\n'+inventoryCode+'\n'+(await fs.readFile(path.join(root,'worker.mjs'),'utf8')).replace(/^import .*;\n/gm,'');
await fs.writeFile(path.join(dest,'index.js'),'const assets='+JSON.stringify(assets)+';\nconst fallback='+JSON.stringify(fallback)+';\n'+sanitizer+'\n'+onlineSales+'\n'+cloudSales+'\n'+eventsData+'\n'+'const profitLossFallback='+JSON.stringify(profitLossFallback)+';\n'+profitLoss+'\n'+proposals+'\n'+rebrand+'\n'+'const productCostFallback='+JSON.stringify(productCostFallback)+';\n'+productCosts+'\n'+'const predictFallback='+JSON.stringify(predictFallback)+';\n'+eventImages+'\n'+predict+'\n'+deletions+'\n'+notifications+'\n'+mobilePush+'\n'+contracts+'\n'+comparisonLive+'\n'+branchStock+'\n'+warehouse+'\n'+stockForecast+'\n'+analysis+'\n'+stockReport+'\n'+accessPermissions+'\n'+activities+'\n'+stockSummary+'\n'+promotionScheduleCode+'\n'+promotionEvents+'\n'+promotions+'\n'+workspaceDrafts+'\n'+summaryDeletions+'\n'+worker);
await fs.rm(path.join(dest,'assets.mjs'),{force:true});
await fs.rm(path.join(dest,'sanitize.mjs'),{force:true});
await fs.mkdir(path.join(root,'dist/.openai'),{recursive:true});await fs.copyFile(path.join(root,'.openai/hosting.json'),path.join(root,'dist/.openai/hosting.json'));
console.log('Built realtime Worker and '+Object.keys(assets).length+' assets');

await fs.rm(path.join(root,'dist/.openai/drizzle'),{recursive:true,force:true});
await fs.cp(path.join(root,'drizzle'),path.join(root,'dist/.openai/drizzle'),{recursive:true});
