import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {previewDatabase} from './preview-db.mjs';
import {loadContractWorkspace as loadContracts,updateContractWorkspace as updateContract} from './contracts-data.mjs';
import worker from './dist/server/index.js';
const base=JSON.parse(await readFile('out/snapshot.json','utf8'));
let saved=structuredClone(base);
const db=previewDatabase();
const env={DB:db,BUCKET:{get:async key=>key==='snapshot.json'?{json:async()=>structuredClone(saved)}:null},SESSION_SECRET:'test-session-only',ADMIN_PASSWORD:'test-admin',VIEWER_PASSWORD:'test-viewer'};
const initial=await loadContracts(env,base,true),row=initial.items[0];
const values=Object.fromEntries(['branch','term','starts_on','ends_on','renewed','status'].map(k=>[k,row[k]]));
values.status='ต่อสัญญาแล้ว';values.term='รอบทดสอบ';values.ends_on='2027-09-30';
const body={key:row.key,revision:row.revision,sourceHash:row.sourceHash,changeId:crypto.randomUUID().replaceAll('-',''),values};
const request=(data=body,extra={})=>new Request('https://example.test/api/contracts',{method:'PATCH',headers:{'content-type':'application/json',origin:'https://example.test',...extra},body:JSON.stringify(data)});
const result=await updateContract(request(),env,base);assert.equal(result.item.revision,body.changeId);
assert.equal((await loadContracts(env,base)).items[0].term,'รอบทดสอบ');
saved.data['/api/contracts'].items[0].term='ชีตใหม่';assert.equal((await loadContracts(env,base)).items[0].term,'รอบทดสอบ');
await assert.rejects(updateContract(request({...body,changeId:crypto.randomUUID().replaceAll('-','')}),env,base),e=>e.status===409);
const latest=(await loadContracts(env,base)).items[0],next={...body,revision:latest.revision,sourceHash:latest.sourceHash,changeId:crypto.randomUUID().replaceAll('-','')};
next.values={...values,term:'การแก้ไขพร้อมกัน'};
const parallel=await Promise.allSettled([updateContract(request(next),env,base),updateContract(request({...next,changeId:crypto.randomUUID().replaceAll('-','')}),env,base)]);assert.equal(parallel.filter(r=>r.status==='fulfilled').length,1);assert.equal(parallel.find(r=>r.status==='rejected').reason.status,409);
for(const invalid of [{ends_on:'2020-01-01'},{branch:''},{status:'unknown'},{renewed:'true'},{starts_on:'2026-02-31'},{extra:'not allowed'}])await assert.rejects(updateContract(request({...next,values:{...values,...invalid}}),env,base),e=>e.status===400);
await assert.rejects(updateContract(request(next,{origin:'https://elsewhere.test'}),env,base),e=>e.status===403);
await assert.rejects(loadContracts({...env,DB:null},base),e=>e.status===503);
// Test actual Worker authorization and origin gates.
assert.equal((await worker.fetch(request(),{...env})).status,401);
const login=async role=>{const response=await worker.fetch(new Request('https://example.test/login',{method:'POST',body:new URLSearchParams({password:env[role==='admin'?'ADMIN_PASSWORD':'VIEWER_PASSWORD']})}),env);return response.headers.get('set-cookie').split(';')[0];};
const viewer=await login('viewer'),admin=await login('admin');
assert.equal((await worker.fetch(request(next,{cookie:viewer}),env)).status,403);
assert.equal((await worker.fetch(request(next,{cookie:admin,origin:'https://elsewhere.test'}),env)).status,403);
const read=await worker.fetch(new Request('https://example.test/api/contracts',{headers:{cookie:viewer}}),env);assert.equal(read.status,200);assert.equal((await read.json()).permissions.canEdit,false);
const fresh=(await loadContracts(env,base)).items[0];const changed={...next,changeId:crypto.randomUUID().replaceAll('-',''),revision:fresh.revision,sourceHash:fresh.sourceHash,values:{...values,term:'บันทึกผ่าน API'}};
const write=await worker.fetch(request(changed,{cookie:admin}),env);assert.equal(write.status,200);assert.equal((await loadContracts(env,base)).items[0].term,'บันทึกผ่าน API');
const badStorage={...env,DB:{prepare(){throw Error('offline');}}};assert.equal((await worker.fetch(request(changed,{cookie:admin}),badStorage)).status,503);
assert.equal((await worker.fetch(new Request('https://example.test/api/contracts',{headers:{cookie:admin}}),badStorage)).status,503);
db.close();console.log('PASS: durable D1 updates, snapshot sync preservation, optimistic concurrency, source revision, date/field validation, admin/viewer/session/origin gates, storage errors');
