import assert from 'node:assert/strict';
import {buildSalesReportModel,summaryMarkup,tableMarkup,selectedReportTable} from './out/assets/daily-sales.mjs';
import {salesExcelSheets,salesExcelWorkbook,selectedSalesSummary} from './out/assets/sales-excel.mjs';
const branch=(name,code,total,type='CDS')=>({branch:name,branch_code:code,type,month_to_date:total,target:500,daily_sales:{'2026-09-30':total}});
const current={year:2026,month:9,latest_date:'2026-09-30',dates:['2026-09-30'],branches:[branch('A','VC-1',120.25),branch('B','VC-2',80),branch('C','VR-3',50,'RBS')]};
const previous={year:2025,month:9,latest_date:'2025-09-30',dates:[],branches:[branch('A','VC-1',100),branch('B','VC-2',100),branch('C','VR-3',100,'RBS')]};
const report={periods:{'2026-09':current,'2025-09':previous}};
const state={year:2026,month:'2026-09',columns:['type','code','total','forecast','yoy','selectedDay','daily'],tableSorts:{main:{key:'total',direction:'asc'}}};
const model=buildSalesReportModel(report,state,'2026-09-30');
assert.equal(model.monthComplete,true);assert.equal(model.useActual,true,'closed current month uses actuals even before calendar rollover');
assert.equal(model.totals.rows.find(r=>r.branch==='A').yoy.delta,20.25);
assert.equal(model.totals.rows.find(r=>r.branch==='B').yoy.percent,-0.2);
assert.match(summaryMarkup(model),/ยอดจริงปิดเดือน/);assert.doesNotMatch(summaryMarkup(model),/<dt>ยอดคาดการณ์รวม/);
assert.match(tableMarkup(model,state,'2026-09-30'),/ยอดจริงเทียบปีก่อน/);
const filters={...state,tableFilters:{main:{type:{values:['text:CDS']}}}};
// Obtain the actual filter token rather than guessing how the UI encodes it.
const {columnChoice}=await import('./out/assets/daily-sales.mjs');
filters.tableFilters.main.type.values=[columnChoice(model.totals.rows.find(r=>r.type==='CDS'),'type').id];
const selected=selectedReportTable(model,filters,'2026-09-30');assert.deepEqual(selected.rows.map(r=>r.branch),['B','A']);
const sheets=salesExcelSheets(model,filters,'2026-09-30'),sheet=sheets[0],summary=sheet.rows.find(r=>r.values[0]==='CDS');
assert.equal(summary.values[2],200.25);assert.equal(summary.values[4],200);assert.equal(summary.values[5],0.25);assert.equal(summary.values[6],0.00125);
assert.deepEqual(sheets.map(s=>s.name),['Sales Report','รายสาขา']);
const detail=sheets[1],header=detail.rows[detail.table.headerRow-1].values;assert(header.includes('ยอดจริงสะสม'));assert(header.includes('ยอดจริงเทียบปีก่อน (%)'));assert(header.includes('2026-09-30'));assert(!header.includes('เป้าหมาย'));
assert.deepEqual(detail.rows.slice(detail.table.headerRow).map(r=>r.values[0]),['B','A']);
assert.equal(detail.freezeRows,detail.table.headerRow);
assert.equal(detail.rows.slice(detail.table.headerRow).reduce((n,r)=>n+r.values[header.indexOf('ยอดรวม')],0),summary.values[2]);
const subset={...filters,branchQuery:'A'};
const subsetRows=selectedReportTable(model,subset,'2026-09-30').rows;
const sub=selectedSalesSummary(model,subsetRows)[0];assert.equal(sub.actual,100);assert.equal(sub.delta,20.25);
const empty=salesExcelSheets(model,{...state,branchQuery:'no match'},'2026-09-30')[0];assert.equal(empty.table,undefined);assert(empty.rows.some(r=>r.values[0]==='ไม่มีรายการที่ตรงกับตัวกรอง'));
const missing=buildSalesReportModel({periods:{'2026-09':current}},state,'2026-10-02');assert.equal(selectedSalesSummary(missing,missing.totals.rows)[0].actual,null);
const zeroPrior={...previous,branches:previous.branches.map(r=>({...r,month_to_date:0}))};const zero=buildSalesReportModel({periods:{...report.periods,'2025-09':zeroPrior}},state,'2026-10-02');assert.equal(selectedSalesSummary(zero,zero.totals.rows)[0].percent,null);
const ongoing=buildSalesReportModel({...report,periods:{...report.periods,'2026-09':{...current,latest_date:'2026-09-29',branches:current.branches.map(r=>({...r,daily_sales:{'2026-09-29':r.month_to_date}}))}}},state,'2026-09-30');assert.equal(ongoing.useActual,false);assert.equal(ongoing.summary.yoySummary.basis,'branch-forecast');
const annual=buildSalesReportModel(report,{...state,month:'all'},'2026-10-02');assert.equal(salesExcelSheets(annual,{...state,month:'all'},'2026-10-02').length,3,'annual daily view includes summary, branches and its monthly daily table');
const bytes=salesExcelWorkbook(model,filters,'2026-09-30'),xml=new TextDecoder().decode(bytes);assert.equal(bytes[0],80);assert.match(xml,/SalesBranches/);assert.match(xml,/<f>D6-E6<\/f>/);assert.match(xml,/<v>120.25<\/v>/);assert.match(xml,/freeze|state="frozen"/);
const dangerous=buildSalesReportModel({periods:{'2026-09':{...current,branches:[branch('=HYPERLINK("test")','000012',10)]}}},state,'2026-10-02');const literal=new TextDecoder().decode(salesExcelWorkbook(dangerous,state,'2026-10-02'));assert.match(literal,/inlineStr[^]*=HYPERLINK/);assert.doesNotMatch(literal,/<f>HYPERLINK/);assert.match(literal,/000012/);
console.log('Closed-month actual YoY, selected outlets/channels/columns/order/days, annual tables, formula totals, typed amounts, unknown baselines and literal text passed');
