import assert from 'node:assert/strict';
import fs from 'node:fs';
import {resolveReportMonth,buildSalesReportModel,filterMarkup} from './out/assets/daily-sales.mjs';
const period=(year,month,total)=>({year,month,latest_date:`${year}-${String(month).padStart(2,'0')}-01`,dates:[`${year}-${String(month).padStart(2,'0')}-01`],branches:[{type:'CDS',branch:'Test branch',branch_code:'VC-999',month_to_date:total,target:1000,daily_sales:{[`${year}-${String(month).padStart(2,'0')}-01`]:total}}]});
const report={periods:{'2026-09':period(2026,9,90),'2026-10':period(2026,10,10)}};
const before={autoMonth:true,year:2026,month:'2026-09',date:'2026-09-30',tableFilters:{main:{branch:{values:['old']}}},branchQuery:'Test'};
const after=resolveReportMonth(before,'2026-10-01');
assert.equal(after.month,'2026-10');assert.equal(after.year,2026);assert.equal(after.date,'');assert.deepEqual(after.tableFilters,{});assert.equal(after.branchQuery,'Test');
assert.equal(before.month,'2026-09','no mutation of prior state');
let model=buildSalesReportModel(report,before,'2026-10-02');
assert.equal(model.month,'2026-10');assert.equal(model.totals.total,10);assert.equal(model.selectedDate,'2026-10-01');
assert.match(filterMarkup(model),/aria-pressed="true"/);
const pinned={...before,autoMonth:false};
model=buildSalesReportModel(report,pinned,'2026-10-02');assert.equal(model.month,'2026-09');assert.equal(model.totals.total,90);
assert.equal(resolveReportMonth({autoMonth:false,year:2026,month:'all'},'2027-01-01').month,'all');
const next=resolveReportMonth(after,'2027-01-01');assert.equal(next.month,'2027-01');assert.equal(next.year,2027);
model=buildSalesReportModel(report,{autoMonth:true},'2027-01-01');
assert.equal(model.month,'2027-01');assert.equal(model.selectedPeriod.awaitingSource,true);assert.equal(model.totals.rows.length,0);assert.equal(model.selectedDate,'');
assert.equal(model.allPeriods.find(p=>p.key==='2026-09').branches[0].month_to_date,90);
model=buildSalesReportModel({...report,periods:{...report.periods,'2027-01':period(2027,1,25)}},next,'2027-01-02');
assert.equal(model.selectedPeriod.awaitingSource,undefined);assert.equal(model.totals.total,25);
const app=fs.readFileSync(new URL('./out/assets/app.mjs',import.meta.url),'utf8');
assert.match(app,/JSON.stringify\(\[values,new Date\(Date.now\(\)\+7\*3600000\)/,'calendar tick must trigger refresh even if snapshot is unchanged');
console.log('Automatic Bangkok month rollover, year rollover, waiting state, arrival and manual history passed');
