import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import worker from './dist/server/index.js';
import {previewDatabase} from './preview-db.mjs';
import {buildSummaryModel,eventOutcomeCounts} from './out/assets/summary-data.mjs';
import {summaryMarkup} from './out/assets/summary.mjs';
import {reportData} from './out/assets/daily-comparison-data.mjs';
const auth={SESSION_SECRET:'delete-test',ADMIN_PASSWORD:'admin-test',VIEWER_PASSWORD:'viewer-test'};
const request=(path,options={})=>new Request('https://example.test'+path,options);
test('Deleting from Summary persists across views and requests, requires edit rights and preserves source financials',async()=>{
 const snapshot=JSON.parse(fs.readFileSync('out/snapshot.json'));
 const pnl=JSON.parse(fs.readFileSync('profit-loss.snapshot.json'));
 const env={...auth,DB:previewDatabase(),BUCKET:{get:async key=>key==='snapshot.json'?{json:async()=>snapshot}:key==='profit-loss.json'?{json:async()=>pnl}:key==='daily-comparison-live.json'?{json:async()=>({...reportData,live:{status:'online',checkedAt:new Date().toISOString()}})}:null,put:async()=>assert.fail('Deletion must not mutate source sheets or snapshots')}};
 const login=async password=>(await worker.fetch(request('/login',{method:'POST',body:new URLSearchParams({password})}),env)).headers.get('set-cookie').split(';')[0];
 const admin=await login(auth.ADMIN_PASSWORD),viewer=await login(auth.VIEWER_PASSWORD);
 const read=async cookie=>await(await worker.fetch(request('/api/summary',{headers:{cookie}}),env)).json();
 const state={year:2026,month:9,basis:'all'};
 const initial=await read(admin),model=buildSummaryModel(initial,state,'2026-09-26');
 const target=model.selected.events.find(item=>/CDS Ladprao/i.test(item.name));assert.ok(target);
 assert.match(summaryMarkup(initial,state),/data-delete-summary-event=/);
 const readOnly=await read(viewer);assert.doesNotMatch(summaryMarkup(readOnly,state),/data-delete-summary-event=/);
 const del=(cookie,origin='https://example.test',key=target.summaryKey)=>worker.fetch(request('/api/summary/events/delete',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:JSON.stringify({key})}),env);
 assert.equal((await del('')).status,401);
 assert.equal((await del(viewer)).status,403);
 assert.equal((await del(admin,'https://untrusted.test')).status,403);
 assert.equal((await del(admin,'https://example.test','unknown')).status,404);
 assert.equal((await worker.fetch(request('/api/summary/events/delete',{headers:{cookie:admin}}),env)).status,405);
 assert.equal((await del(admin)).status,200);assert.equal((await del(admin)).status,200);
 const after=await read(viewer),next=buildSummaryModel(after,state,'2026-09-26');
 assert.ok(after.deletedSummaryEvents.includes(target.summaryKey));
 assert.equal(next.selected.events.length,model.selected.events.length-1);
 assert.equal(eventOutcomeCounts(next.selected.events,next.eventRecords,2026).total,model.selected.events.length-1);
 assert.ok(!next.monthly.some(month=>month.events.some(item=>item.summaryKey===target.summaryKey)));
 assert.deepEqual(after.events,initial.events);assert.deepEqual(after.pnl,initial.pnl);
 assert.equal(next.selected.finance.profit,model.selected.finance.profit);
 assert.equal((await env.DB.prepare('SELECT id FROM summary_event_deletions').all()).results.length,1);
 const originalPrepare=env.DB.prepare;
 env.DB.prepare=sql=>{if(sql.includes('summary_event_deletions'))throw Error('storage unavailable');return originalPrepare(sql);};
 assert.equal((await worker.fetch(request('/api/summary',{headers:{cookie:admin}}),env)).status,503);
 assert.equal((await del(admin)).status,503);
 env.DB.close();
});
test('Approved proposals can be removed from every scheduled month without deleting the proposal',()=>{
 const proposal={deletionKey:'web:proposal',trade:'อนุมัติ',ceo:'อนุมัติ',name:'งานทดสอบ',startDate:'2026-09-28',endDate:'2026-10-05',sourceYear:2026};
 const data={comparison:null,approvedProposals:[proposal],permissions:{canEdit:true}};
 const initial=buildSummaryModel(data,{year:2026,month:9},'2026-09-26');
 const key=initial.selected.events[0].summaryKey;
 const after=buildSummaryModel({...data,deletedSummaryEvents:[key]},{year:2026,month:10},'2026-09-26');
 assert.equal(after.selected.events.length,0);assert.equal(after.monthly[8].events.length,0);
 assert.equal(data.approvedProposals.length,1);
});
